const d = (s) => new Date(s).getTime();

export const DEMO_FRIENDS = [
  {
    id: "friend-john",
    name: "John Lennon",
    email: "john@beatles.com",
    phone: "",
    contact: "@johnlennon",
    notes: "Brilliant but unpredictable. Needs some notice. Worth it every time.",
    status: "Close friend",
    wantAround: "active",
    busyUntil: null,
    reliability: 3,
    responsiveness: 2,
    vibe: 5,
    openness: 4,
    logistics: 3,
    interests: { concerts: 5, "bars-drinks": 4, "just-hang": 4, food: 3, "house-party": 3 },
    groups: ["beatles"],
    tags: ["musician", "creative"],
    targetFreqDays: 14,
    availSlots: ["weekday-evening", "weekend-evening"],
    distanceTier: "driving",
    comfortLevel: "solo",
    socialType: "ambivert",
    workDrain: "medium",
    noticePreference: "few-days",
    locationPref: "out",
    preferredChannel: "imessage",
    conflicts: [],
    synergies: ["friend-paul"],
    lastHangDate: "2026-05-06",
    rankings: {},
    manualFlakes: 0,
    updatedAt: d("2026-06-01"),
  },
  {
    id: "friend-paul",
    name: "Paul McCartney",
    email: "paul@beatles.com",
    phone: "",
    contact: "@paulmccartney",
    notes: "Always down to hang. Best for food and games. Extremely reliable.",
    status: "Close friend",
    wantAround: "active",
    busyUntil: null,
    reliability: 5,
    responsiveness: 5,
    vibe: 5,
    openness: 5,
    logistics: 4,
    interests: { food: 5, "board-games": 5, concerts: 4, "bars-drinks": 3, coffee: 4 },
    groups: ["beatles"],
    tags: ["musician", "foodie"],
    targetFreqDays: 7,
    availSlots: ["weekday-evening", "weekend-day", "weekend-evening"],
    distanceTier: "local",
    comfortLevel: "solo",
    socialType: "extrovert",
    workDrain: "low",
    noticePreference: "spontaneous",
    locationPref: "out",
    preferredChannel: "imessage",
    conflicts: [],
    synergies: ["friend-john"],
    lastHangDate: "2026-06-14",
    rankings: {},
    manualFlakes: 0,
    updatedAt: d("2026-06-14"),
  },
  {
    id: "friend-george",
    name: "George Harrison",
    email: "george@beatles.com",
    phone: "",
    contact: "@georgeharrison",
    notes: "Introverted, needs planning ahead. Loves coffee and hiking. Recharges solo.",
    status: "Friend",
    wantAround: "active",
    busyUntil: null,
    reliability: 4,
    responsiveness: 3,
    vibe: 4,
    openness: 3,
    logistics: 4,
    interests: { coffee: 5, hiking: 5, concerts: 4, "just-hang": 3, "board-games": 3 },
    groups: ["beatles"],
    tags: ["musician", "spiritual"],
    targetFreqDays: 30,
    availSlots: ["weekend-day"],
    distanceTier: "nearby",
    comfortLevel: "familiar",
    socialType: "introvert",
    workDrain: "high",
    noticePreference: "planned",
    locationPref: "either",
    preferredChannel: "imessage",
    conflicts: ["friend-yoko"],
    synergies: [],
    lastHangDate: "2026-03-24",
    rankings: {},
    manualFlakes: 0,
    updatedAt: d("2026-03-24"),
  },
  {
    id: "friend-ringo",
    name: "Ringo Starr",
    email: "ringo@beatles.com",
    phone: "",
    contact: "@ringostarr",
    notes: "Super social, almost always down. Flaked once but usually solid.",
    status: "Friend",
    wantAround: "active",
    busyUntil: null,
    reliability: 4,
    responsiveness: 4,
    vibe: 4,
    openness: 5,
    logistics: 3,
    interests: { sports: 5, "house-party": 5, "bars-drinks": 4, concerts: 4, food: 3 },
    groups: ["beatles"],
    tags: ["musician", "social"],
    targetFreqDays: 14,
    availSlots: ["weekday-evening", "weekend-day", "weekend-evening"],
    distanceTier: "local",
    comfortLevel: "solo",
    socialType: "extrovert",
    workDrain: "low",
    noticePreference: "spontaneous",
    locationPref: "out",
    preferredChannel: "imessage",
    conflicts: [],
    synergies: [],
    lastHangDate: "2026-06-02",
    rankings: {},
    manualFlakes: 1,
    updatedAt: d("2026-06-02"),
  },
  {
    id: "friend-yoko",
    name: "Yoko Ono",
    email: "yoko@ono.com",
    phone: "",
    contact: "@yokoono",
    notes: "Creative and interesting but hard to pin down. Needs a +1 to feel comfortable.",
    status: "Acquaintance",
    wantAround: "active",
    busyUntil: null,
    reliability: 2,
    responsiveness: 3,
    vibe: 3,
    openness: 4,
    logistics: 2,
    interests: { "just-hang": 3, coffee: 3, concerts: 4 },
    groups: [],
    tags: ["artist"],
    targetFreqDays: 60,
    availSlots: ["weekend-evening"],
    distanceTier: "driving",
    comfortLevel: "needs-plus1",
    socialType: "introvert",
    workDrain: "high",
    noticePreference: "planned",
    locationPref: "out",
    preferredChannel: "imessage",
    conflicts: ["friend-george"],
    synergies: [],
    lastHangDate: "2025-12-15",
    rankings: {},
    manualFlakes: 1,
    updatedAt: d("2025-12-15"),
  },
];

export const DEMO_EVENTS = [
  {
    id: "event-concert",
    title: "Rooftop Concert",
    activityId: "concerts",
    date: "2026-04-23",
    startTime: "20:00",
    endTime: "23:00",
    location: "The Cavern Rooftop",
    cascade: false,
    finalized: true,
    notes: "Classic.",
    invites: [
      {
        friendId: "friend-john",
        inviteStatus: "accepted",
        response: "yes",
        queuePosition: 1,
        inviteSentAt: d("2026-04-16"),
        respondedAt: d("2026-04-17"),
        attendingLegs: null,
      },
      {
        friendId: "friend-paul",
        inviteStatus: "accepted",
        response: "yes",
        queuePosition: 2,
        inviteSentAt: d("2026-04-16"),
        respondedAt: d("2026-04-18"),
        attendingLegs: null,
      },
      {
        friendId: "friend-george",
        inviteStatus: "declined",
        response: "no",
        queuePosition: 3,
        inviteSentAt: d("2026-04-16"),
        respondedAt: d("2026-04-19"),
        attendingLegs: null,
      },
      {
        friendId: "friend-ringo",
        inviteStatus: "ghosted",
        response: null,
        queuePosition: 4,
        inviteSentAt: d("2026-04-16"),
        respondedAt: null,
        attendingLegs: null,
      },
    ],
  },
  {
    id: "event-boardgames",
    title: "Abbey Road Board Game Night",
    activityId: "board-games",
    date: "2026-05-28",
    startTime: "19:00",
    endTime: "23:00",
    location: "Paul's place",
    cascade: false,
    finalized: true,
    notes: "Wingspan and Ticket to Ride.",
    invites: [
      {
        friendId: "friend-paul",
        inviteStatus: "accepted",
        response: "yes",
        queuePosition: 1,
        inviteSentAt: d("2026-05-22"),
        respondedAt: d("2026-05-23"),
        attendingLegs: null,
      },
      {
        friendId: "friend-george",
        inviteStatus: "accepted",
        response: "yes",
        queuePosition: 2,
        inviteSentAt: d("2026-05-22"),
        respondedAt: d("2026-05-24"),
        attendingLegs: null,
      },
      {
        friendId: "friend-ringo",
        inviteStatus: "accepted",
        response: "yes",
        queuePosition: 3,
        inviteSentAt: d("2026-05-22"),
        respondedAt: d("2026-05-23"),
        attendingLegs: null,
      },
    ],
  },
  {
    id: "event-bbq",
    title: "July 4th BBQ",
    activityId: "house-party",
    date: "2026-07-04",
    startTime: "15:00",
    endTime: "21:00",
    location: "John's backyard",
    cascade: false,
    finalized: false,
    notes: "Bring something to grill.",
    invites: [
      {
        friendId: "friend-paul",
        inviteStatus: "accepted",
        response: "yes",
        queuePosition: 1,
        inviteSentAt: d("2026-06-15"),
        respondedAt: d("2026-06-17"),
        attendingLegs: null,
      },
      {
        friendId: "friend-ringo",
        inviteStatus: "accepted",
        response: "yes",
        queuePosition: 2,
        inviteSentAt: d("2026-06-15"),
        respondedAt: d("2026-06-18"),
        attendingLegs: null,
      },
      {
        friendId: "friend-john",
        inviteStatus: "invited",
        response: null,
        queuePosition: 3,
        inviteSentAt: d("2026-06-15"),
        respondedAt: null,
        attendingLegs: null,
      },
      {
        friendId: "friend-george",
        inviteStatus: "invited",
        response: null,
        queuePosition: 4,
        inviteSentAt: d("2026-06-15"),
        respondedAt: null,
        attendingLegs: null,
      },
    ],
  },
  {
    id: "event-dinner-cascade",
    title: "Intimate Dinner",
    activityId: "food",
    date: "2026-07-15",
    startTime: "18:30",
    endTime: "20:30",
    location: "The Maharaja",
    cascade: true,
    finalized: false,
    notes: "Small group. Cascade to fill the last seat.",
    invites: [
      {
        friendId: "friend-paul",
        inviteStatus: "accepted",
        response: "yes",
        queuePosition: 1,
        inviteSentAt: d("2026-06-01"),
        respondedAt: d("2026-06-03"),
        attendingLegs: null,
      },
      {
        friendId: "friend-john",
        inviteStatus: "invited",
        response: null,
        queuePosition: 2,
        inviteSentAt: d("2026-06-20"),
        respondedAt: null,
        attendingLegs: null,
      },
      {
        friendId: "friend-ringo",
        inviteStatus: "queued",
        response: null,
        queuePosition: 3,
        inviteSentAt: null,
        respondedAt: null,
        attendingLegs: null,
      },
      {
        friendId: "friend-yoko",
        inviteStatus: "queued",
        response: null,
        queuePosition: 4,
        inviteSentAt: null,
        respondedAt: null,
        attendingLegs: null,
      },
    ],
  },
];

export async function seedDemoDataIfEmpty(db) {
  if (localStorage.getItem("fr:demo-dismissed")) return;
  const existing = await db.getAll("friends");
  if (existing.length > 0) return;
  const tx1 = db.transaction("friends", "readwrite");
  for (const f of DEMO_FRIENDS) tx1.store.put(f);
  await tx1.done;
  const tx2 = db.transaction("events", "readwrite");
  for (const e of DEMO_EVENTS) tx2.store.put(e);
  await tx2.done;
}
